- docs/decisions/0002-asynchronous-processing.rst
**Description:** Adding a new ADR that will codify our decision to use an asynchronous processing model for Commerce Coordinator based upon Celery.
**JIRA:** REV-2404
> docs: ADR-2 on using asynchronous processing and Celery

- README.rst
**Jira ticket:** [REV-2480](https://openedx.atlassian.net/browse/REV-2480)
**Description:** 
I updated the README based on info from [PR7](https://github.com/edx/commerce-coordinator/pull/7) plus the steps we've established this week for getting commerce-coordinator to run locally, and minus two recommendations in Brian's list of concerns that are already in progress ([REV-2483](https://openedx.atlassian.net/browse/REV-2483) and [REV-2484](https://openedx.atlassian.net/browse/REV-2484)). 
- [n/a] CI build is green- docs check has known failure (REV-2615), can check quality after Ben's [PR with fix](https://github.com/edx/commerce-coordinator/pull/10) is ready
> REV-2400: Update README

- .gitignore
- .vscode/settings.json
> fix: ignore .vscode

- commerce_coordinator/apps/titan/admin.py
- commerce_coordinator/apps/titan/apps.py
- commerce_coordinator/apps/titan/models.py
- commerce_coordinator/apps/titan/tests/__init__.py
- commerce_coordinator/apps/titan/tests/test_views.py
- commerce_coordinator/apps/titan/urls.py
- commerce_coordinator/apps/titan/views.py
- docs/commerce_coordinator.apps.rst
- docs/commerce_coordinator.apps.titan.migrations.rst
- docs/commerce_coordinator.apps.titan.tests.rst
**Description:** adding a titan app for the Theseus POC workshop and beyond!
> Add titan app placeholder files

- commerce_coordinator/apps/demo_lms/apps.py
- commerce_coordinator/apps/demo_lms/views.py
- commerce_coordinator/apps/lms/admin.py
- commerce_coordinator/apps/lms/apps.py
- commerce_coordinator/apps/lms/models.py
- commerce_coordinator/apps/lms/tests.py
- commerce_coordinator/apps/lms/urls.py
- commerce_coordinator/apps/lms/views.py
- commerce_coordinator/apps/titan/signals.py
- commerce_coordinator/settings/base.py
- commerce_coordinator/settings/local.py
- commerce_coordinator/urls.py
- docs/commerce_coordinator.apps.rst
[REV-2847](https://2u-internal.atlassian.net/browse/REV-2847).
Hackathon work for the Theseus Project, adding the LMS app to commerce-coordinator.
**This PR:**
- Renames LmsConfig in `demo_lms` to DemoLmsConfig to match app name
- Fixes some import errors in other apps
- Adds the LMS app (initial files, urls.py, and views.py)
There are no tests and no testing for this initial commit for the LMS app.
> feat: Add LMS app

- commerce_coordinator/apps/demo_lms/admin.py
- commerce_coordinator/apps/demo_lms/apps.py
- commerce_coordinator/apps/demo_lms/models.py
- commerce_coordinator/apps/demo_lms/tasks.py
- commerce_coordinator/apps/demo_lms/tests.py
- commerce_coordinator/apps/demo_lms/views.py
- commerce_coordinator/apps/ecommerce/views.py
Fixing some typos and docstring updates I found throughout commerce-coordinator (not related to any specific work).
> fix: Misc typos

- openedx.yaml
Updating release metadata ahead of Olive.
> build: this repo isn't yet ready to be included in Open edX

- .github/workflows/ci.yml
- .github/workflows/docker-publish.yml
[REV-3283](https://2u-internal.atlassian.net/browse/REV-3283)
> build: add 2u/project-theseus branch to run ci

- docs/decisions/0005-caching.rst
**JIRA:** [THES-71](https://2u-internal.atlassian.net/browse/THES-71)
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> feat: Added caching ADR.

- .coveragerc
- commerce_coordinator/apps/core/clients.py
- commerce_coordinator/apps/core/tests/utils.py
- commerce_coordinator/apps/ecommerce/clients.py
- commerce_coordinator/apps/ecommerce/tests/test_clients.py
- commerce_coordinator/apps/lms/clients.py
- commerce_coordinator/apps/lms/tests/constants.py
- commerce_coordinator/apps/lms/tests/test_clients.py
- commerce_coordinator/apps/lms/tests/test_signals.py
- commerce_coordinator/apps/lms/tests/test_tasks.py
- commerce_coordinator/apps/titan/clients.py
- commerce_coordinator/apps/titan/tests/test_clients.py
[THES-154](https://2u-internal.atlassian.net/browse/THES-154) (Tests: Finish refactoring tests to use new CoordinatorClientTestCase and CoordinatorSignalTestCase)
> test: add LMS test_clients.py, test_signals.py, test_tasks.py

- commerce_coordinator/apps/core/tests/utils.py
- commerce_coordinator/apps/titan/tests/constants.py
- commerce_coordinator/apps/titan/tests/test_views.py
- commerce_coordinator/apps/titan/views.py
- docs/commerce_coordinator.apps.core.rst
- docs/commerce_coordinator.apps.core.tests.rst
- docs/commerce_coordinator.apps.lms.rst
- docs/commerce_coordinator.apps.titan.rst
- docs/commerce_coordinator.apps.titan.tests.rst
Add Titan tests for OrderFulfillViewTests.
* Jira: [THES-154](https://2u-internal.atlassian.net/browse/THES-154)
> tests: add titan OrderFulfillViewTests

- README.rst
THES-178:Updating Readme for Local Installation, including the deprecation for now of the Docker portion until we get it working once again.
> THES-178:Updating Readme for Local Installation

- .coveragerc
- commerce_coordinator/apps/core/cache.py
- commerce_coordinator/apps/core/constants.py
- commerce_coordinator/apps/core/memcache.py
- commerce_coordinator/apps/core/tests/test_memcache.py
- commerce_coordinator/apps/core/tests/utils.py
- commerce_coordinator/apps/ecommerce/views.py
- commerce_coordinator/apps/frontend_app_payment/admin.py
- commerce_coordinator/apps/frontend_app_payment/apps.py
- commerce_coordinator/apps/frontend_app_payment/exceptions.py
- commerce_coordinator/apps/frontend_app_payment/filters.py
- commerce_coordinator/apps/frontend_app_payment/models.py
- commerce_coordinator/apps/frontend_app_payment/serializers.py
- commerce_coordinator/apps/frontend_app_payment/tests/__init__.py
- commerce_coordinator/apps/frontend_app_payment/tests/test_views.py
- commerce_coordinator/apps/frontend_app_payment/urls.py
- commerce_coordinator/apps/frontend_app_payment/views.py
- commerce_coordinator/apps/titan/clients.py
- commerce_coordinator/apps/titan/exceptions.py
- commerce_coordinator/apps/titan/pipeline.py
- commerce_coordinator/apps/titan/tests/test_clients.py
- commerce_coordinator/apps/titan/tests/test_pipeline.py
- commerce_coordinator/settings/base.py
- commerce_coordinator/settings/local.py
- commerce_coordinator/settings/test.py
- commerce_coordinator/urls.py
- docs/commerce_coordinator.apps.frontend_app_payment.migrations.rst
- docs/commerce_coordinator.apps.frontend_app_payment.rst
- docs/commerce_coordinator.apps.frontend_app_payment.tests.rst
Also added memcache utils, memcached tests, Throttle etc.
**JIRA:** [THES-57](https://2u-internal.atlassian.net/browse/THES-57)
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> feat: Added GET Payment (State) API.

- commerce_coordinator/apps/titan/clients.py
- commerce_coordinator/apps/titan/tests/test_clients.py
**JIRA:** [Link to JIRA ticket](https://2u-internal.atlassian.net/browse/THES-168)
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> feat: implemented TitanAPIClient.update_payment method.

- commerce_coordinator/apps/titan/tasks.py
- commerce_coordinator/apps/titan/tests/test_tasks.py
**JIRA:** Link to JIRA ticket
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> feat: implemented payment_processed_save_task.

- commerce_coordinator/apps/core/constants.py
- commerce_coordinator/apps/titan/clients.py
- commerce_coordinator/apps/titan/tests/test_clients.py
[THES-190](https://2u-internal.atlassian.net/browse/THES-190)
Implements [Create Payment (commerce-coordinator → titan)](https://github.com/edx/commerce-coordinator-private/blob/a740ebf00ffee93efac0a61c7ed47293f21511b6/docs/api-spec/theseus-api-spec.md#action-create-payment).
> feat: implemented TitanAPIClient.create_payment.

- commerce_coordinator/apps/frontend_app_payment/filters.py
- commerce_coordinator/apps/frontend_app_payment/tests/test_filters.py
- commerce_coordinator/apps/titan/pipeline.py
- commerce_coordinator/settings/base.py
Implemented frontend-app-payment.filters.DraftPaymentRequested → titan.pipeline.GetTitanPayment
**JIRA:** [THES-181](https://2u-internal.atlassian.net/browse/THES-181)
> feat: Added DraftPaymentRequested filter.

- commerce_coordinator/apps/frontend_app_payment/exceptions.py
- commerce_coordinator/apps/frontend_app_payment/filters.py
- commerce_coordinator/apps/frontend_app_payment/serializers.py
- commerce_coordinator/apps/frontend_app_payment/tests/test_filters.py
- commerce_coordinator/apps/frontend_app_payment/tests/test_views.py
- commerce_coordinator/apps/frontend_app_payment/urls.py
- commerce_coordinator/apps/frontend_app_payment/views.py
- commerce_coordinator/apps/titan/pipeline.py
- commerce_coordinator/apps/titan/serializers.py
- commerce_coordinator/apps/titan/tests/test_clients.py
- commerce_coordinator/apps/titan/tests/test_pipeline.py
**Description:** Added DraftPaymentCreateView
**JIRA:** [THES-180](https://2u-internal.atlassian.net/browse/THES-180)
> feat: DraftPaymentCreateView added.

- commerce_coordinator/apps/frontend_app_payment/filters.py
- commerce_coordinator/apps/frontend_app_payment/serializers.py
- commerce_coordinator/apps/frontend_app_payment/tests/test_filters.py
- commerce_coordinator/apps/frontend_app_payment/tests/test_views.py
- commerce_coordinator/apps/frontend_app_payment/urls.py
- commerce_coordinator/apps/frontend_app_payment/views.py
- commerce_coordinator/apps/titan/pipeline.py
**Description:** 
Implemented views.PaymentProcessView
Implemented serializer for views.PaymentProcessView
Implemented filters.PaymentProcessingRequested (left without connecting pipeline steps)
Created unit test for view
**JIRA:** https://2u-internal.atlassian.net/browse/THES-199
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
solutions, hacks, quick-and-dirty implementations, concerns about …
> feat: Added PaymentProcessView and PaymentProcessInputSerializer

- commerce_coordinator/apps/titan/pipeline.py
- commerce_coordinator/apps/titan/tests/test_pipeline.py
- commerce_coordinator/settings/base.py
[THES-201](https://2u-internal.atlassian.net/browse/THES-201)
Adds the Update Billing Address Pipeline step
> feat: Add Pipeline step for UpdateBillingAddress

- commerce_coordinator/apps/frontend_app_payment/exceptions.py
- commerce_coordinator/apps/frontend_app_payment/filters.py
- commerce_coordinator/apps/frontend_app_payment/tests/test_filters.py
- commerce_coordinator/apps/frontend_app_payment/tests/test_views.py
- commerce_coordinator/apps/frontend_app_payment/views.py
- commerce_coordinator/apps/titan/exceptions.py
- commerce_coordinator/apps/titan/pipeline.py
- commerce_coordinator/apps/titan/tests/test_pipeline.py
- commerce_coordinator/settings/base.py
- docs/commerce_coordinator.apps.frontend_app_payment.rst
**Description:**
* added GetTitanPayment in base.py settings
* moved InvalidOrderPayment in GetTitanPayment
* updated GetTitanPayment to handle exceptions
* updated existing tests and added new tests as well.
**JIRA:** [Link to JIRA ticket](https://2u-internal.atlassian.net/browse/THES-203)
> feat: Connected frontend-app-payment.filters.PaymentProcessingRequested → titan.pipeline.GetTitanPayment

- commerce_coordinator/apps/ecommerce/serializers.py
- commerce_coordinator/apps/ecommerce/tests/test_views.py
- commerce_coordinator/apps/ecommerce/views.py
- commerce_coordinator/apps/lms/serializers.py
- commerce_coordinator/apps/lms/tests/test_views.py
- commerce_coordinator/apps/lms/views.py
- commerce_coordinator/apps/titan/clients.py
- commerce_coordinator/apps/titan/signals.py
- commerce_coordinator/apps/titan/tasks.py
- commerce_coordinator/apps/titan/tests/test_clients.py
- commerce_coordinator/apps/titan/tests/test_tasks.py
**Description:** Our existing code is using `sku` param name so we had to rename `product_sku` to `sku`. 
**JIRA:** [THES-68](https://2u-internal.atlassian.net/browse/THES-68)
> fix: renamed product_sku to sku

- commerce_coordinator/apps/frontend_app_payment/filters.py
- commerce_coordinator/apps/frontend_app_payment/tests/test_filters.py
- commerce_coordinator/apps/titan/pipeline.py
- commerce_coordinator/apps/titan/tests/test_pipeline.py
- commerce_coordinator/settings/base.py
[THES-204](https://2u-internal.atlassian.net/browse/THES-204)
This PR adds the Update Payment api call to the mark payment as ready for processing pipeline flow.
> feat: Add update payment pipleine to mark payment ready for processing

- commerce_coordinator/apps/stripe/clients.py
- commerce_coordinator/apps/stripe/exceptions.py
- commerce_coordinator/apps/stripe/pipeline.py
- commerce_coordinator/apps/stripe/tests/test_clients.py
- commerce_coordinator/apps/stripe/tests/test_pipeline.py
* Implemented StripeAPIClient.confirm_payment_intent
* Implemented pipeline.ConfirmPayment
* Implemented unittests for StripeAPIClient.confirm_payment_intent
**JIRA:** Link to JIRA ticket
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> feat: Implemented StripeAPIClient.confirm_payment_intent

- commerce_coordinator/apps/stripe/tests/test_pipeline.py
**JIRA:** Link to JIRA ticket
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> fix: added reset_mock.

- commerce_coordinator/apps/lms/tests/test_views.py
- commerce_coordinator/apps/lms/views.py
> chore: Fixing use of `Enum` as Strings (have to call `.value`)

- commerce_coordinator/apps/stripe/pipeline.py
- commerce_coordinator/apps/stripe/tests/test_pipeline.py
- commerce_coordinator/apps/stripe/tests/test_utils.py
- commerce_coordinator/apps/stripe/tests/test_views.py
- commerce_coordinator/apps/stripe/utils.py
- commerce_coordinator/apps/stripe/views.py
- commerce_coordinator/apps/titan/filters.py
- commerce_coordinator/apps/titan/signals.py
- commerce_coordinator/apps/titan/tasks.py
- commerce_coordinator/apps/titan/tests/test_tasks.py
- commerce_coordinator/settings/base.py
* Added PaymentSuperseded filter
* Added UpdateStripePayment pipelinestep
* Updated payment_processed_save_task to add call to PaymentSuperseded
* Added util for sanitize_provider_response_body
* fixed order_number metadata in webhook
* added and updated unit tests.
**JIRA:** Link to JIRA ticket
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
**Author concerns:** List any concerns about this PR …
> feat: Added PaymentSuperseded filter.

- Makefile
Part of THES-261.
Related to: https://github.com/openedx/edx-cookiecutters/issues/384
> fix: Cookie Cutter changes broke Jenkins.

- commerce_coordinator/apps/core/cache.py
- commerce_coordinator/apps/core/tests/test_cache.py
- commerce_coordinator/apps/frontend_app_payment/exceptions.py
- commerce_coordinator/apps/frontend_app_payment/filters.py
- commerce_coordinator/apps/frontend_app_payment/serializers.py
- commerce_coordinator/apps/frontend_app_payment/tests/test_filters.py
- commerce_coordinator/apps/frontend_app_payment/tests/test_views.py
- commerce_coordinator/apps/frontend_app_payment/views.py
- commerce_coordinator/apps/titan/pipeline.py
- commerce_coordinator/apps/titan/serializers.py
- commerce_coordinator/apps/titan/tasks.py
- commerce_coordinator/apps/titan/tests/test_pipeline.py
- commerce_coordinator/apps/titan/tests/test_tasks.py
- commerce_coordinator/settings/base.py
**Description:** Restructured caching
* Created Utils for setting cache and getting cache in our core app.
* Added CachedPaymentSerializer in all our caches to make sure caches are consistent.
* Added `new_payment_number` in our caching on both places(webhook and get payment view.)
* Fixed "Mark Payment Ready for Processing" view. We were not providing `payment_state`. So rename `UpdateTitanPayment` to `MarkTitanPaymentPending` and payment state there.
* There are some other minor fixes.
**JIRA:** [THES-239](https://2u-internal.atlassian.net/browse/THES-239)
> feat: restructured caching.

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/frontend_app_ecommerce/tests/test_filters.py
- commerce_coordinator/apps/frontend_app_ecommerce/tests/test_views.py
- commerce_coordinator/apps/rollout/pipeline.py
- commerce_coordinator/apps/rollout/waffle.py
[WIP]
**Description:** Conditionally routing learners to the CT checkout page based on waffle toggle status. 
**JIRA:** [SONIC-100](https://2u-internal.atlassian.net/browse/SONIC-100)
**Dependencies:** dependencies on other outstanding PRs, issues, etc.
> feat: Checks for redirecting to CT checkout

- commerce_coordinator/apps/commercetools_frontend/constants.py
- commerce_coordinator/apps/commercetools_frontend/pipeline.py
- commerce_coordinator/apps/frontend_app_payment/constants.py
- commerce_coordinator/apps/frontend_app_payment/pipeline.py
- commerce_coordinator/apps/lms/filters.py
- commerce_coordinator/apps/lms/tests/test_views.py
- commerce_coordinator/apps/lms/urls.py
- commerce_coordinator/apps/lms/views.py
- commerce_coordinator/apps/rollout/pipeline.py
- commerce_coordinator/settings/base.py
**Description:** [WIP] Created endpoint to route learners to correct checkout page
**JIRA:** [SONIC-122](https://2u-internal.atlassian.net/browse/SONIC-122)
> feat: Created endpoint to route learners to correct checkout page

- Dockerfile
Remove trailing backslash causing Dockerfile error.
Fixes error:
E: Unable to locate package RUN
E: Unable to locate package install
E: Unable to locate package setuptools
The command '/bin/sh -c apt-get update && apt-get -qy install --no-install-recommends  gcc  git  language-pack-en  libmysqlclient-dev  libssl-dev  locales  pkg-config  python3-dev  python3-pip  python3.8 RUN pip install --upgrade pip setuptools' returned a non-zero code: 100
* Jira: [SONIC-169](https://2u-internal.atlassian.net/browse/SONIC-169)
* Fix for #134 
Tested on local by running `docker-compose build`, seeing error, then applying fix and running same command successfully.
<details>
<summary>`docker-compose build` output on local</summary>
```
commerce-coordinator % docker-compose build
db uses an image, …
```
> fix: [SONIC-169] remove trailing backslash causing Dockerfile error

- commerce_coordinator/apps/commercetools/catalog_info/constants.py
- commerce_coordinator/apps/commercetools/catalog_info/edx_utils.py
- commerce_coordinator/apps/commercetools/catalog_info/utils.py
- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/serializers.py
- commerce_coordinator/apps/commercetools/tests/catalog_info/test_edx_utils.py
- commerce_coordinator/apps/commercetools/tests/conftest.py
- commerce_coordinator/apps/commercetools/tests/raw_ct_order.json
- commerce_coordinator/apps/commercetools/tests/test_data.py
- commerce_coordinator/apps/commercetools/tests/test_views.py
- commerce_coordinator/apps/commercetools/views.py
- docs/commerce_coordinator.apps.commercetools.rst
- docs/commerce_coordinator.apps.commercetools.tests.catalog_info.rst
- docs/commerce_coordinator.apps.commercetools.tests.rst
- docs/commerce_coordinator.apps.frontend_app_payment.rst
SONIC-120 with some work completed for SONIC-117
> feat: Baseline pulling of Order Fulfillment Parameters

- commerce_coordinator/apps/commercetools_frontend/pipeline.py
- commerce_coordinator/apps/frontend_app_payment/pipeline.py
- commerce_coordinator/apps/lms/tests/test_views.py
- commerce_coordinator/apps/lms/urls.py
- commerce_coordinator/apps/lms/views.py
- commerce_coordinator/apps/rollout/pipeline.py
- commerce_coordinator/settings/base.py
> fix: Fixed settings flags and return URL for checkout redirect endpoint

- commerce_coordinator/settings/base.py
- commerce_coordinator/settings/local.py
Remove setting `PAYMENT_MICROFRONTEND_URL`, as it is a duplicate of `FRONTEND_APP_PAYMENT_URL`.
* Jira: [SONIC-166](https://2u-internal.atlassian.net/browse/SONIC-166)
> feat: [SONIC-166] cleanup duplicate setting PAYMENT_MICROFRONTEND_URL

- commerce_coordinator/apps/commercetools/tests/test_utils.py
- commerce_coordinator/apps/commercetools/utils.py
- commerce_coordinator/settings/base.py
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
> feat: [SONIC-157] configure braze client

- commerce_coordinator/apps/lms/tests/test_views.py
- commerce_coordinator/apps/rollout/pipeline.py
- commerce_coordinator/settings/base.py
- commerce_coordinator/settings/local.py
> fix: Merge 2u/sandbox-lightweight-prototype into main

- commerce_coordinator/apps/lms/tasks.py
- commerce_coordinator/apps/lms/tests/constants.py
> fix: fix date_placed for enrollment call

- commerce_coordinator/apps/enterprise_learner/enterprise_client.py
- commerce_coordinator/apps/enterprise_learner/tests/test_enterprise_client.py
- commerce_coordinator/apps/enterprise_learner/utils.py
- commerce_coordinator/apps/lms/tests/test_views.py
- commerce_coordinator/apps/rollout/pipeline.py
- commerce_coordinator/settings/base.py
- commerce_coordinator/settings/test.py
**Description**: Added missing unittest from SONIC-123 and minor changes
**JIRA**: [SONIC-251](https://2u-internal.atlassian.net/browse/SONIC-251)
> feat: Added unittest to test_views.py

- .coveragerc
- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/tests/test_views.py
- commerce_coordinator/apps/commercetools/views.py
- commerce_coordinator/apps/core/signals.py
- commerce_coordinator/apps/core/tasks.py
- commerce_coordinator/apps/lms/clients.py
- commerce_coordinator/celery.py
https://github.com/edx/commerce-coordinator/pull/162/files#r1484090622
> fix: changes suggested by Shafqat after PR merge for SONIC-165

- commerce_coordinator/apps/commercetools/views.py
Something missed in https://github.com/edx/commerce-coordinator/pull/168
> fix: typos in text and properties.

- commerce_coordinator/apps/stripe/clients.py
- commerce_coordinator/apps/stripe/constants.py
- commerce_coordinator/apps/stripe/tests/test_clients.py
**Description**: Added method to Stripe client that creates a refund for the given order.
**JIRA**: [SONIC-84](https://2u-internal.atlassian.net/browse/SONIC-84)
> feat: Added issue_credit method to Stripe client

- commerce_coordinator/apps/commercetools/catalog_info/edx_utils.py
- commerce_coordinator/apps/commercetools/tests/test_views.py
- commerce_coordinator/apps/commercetools/urls.py
- commerce_coordinator/apps/commercetools/views.py
- commerce_coordinator/apps/ecommerce/pipeline.py
From Abandoned: https://github.com/edx/commerce-coordinator/pull/177
Code for a basic Returned view
SONIC-260
Depends: 
- https://github.com/edx/commerce-coordinator/pull/171
- https://github.com/edx/terraform/pull/6686
Related:
- https://github.com/edx/commerce-coordinator/pull/172
- https://github.com/edx/commerce-coordinator/pull/176
> feat: adding basic view for Returned and testing

- commerce_coordinator/apps/commercetools/tests/test_utils.py
- commerce_coordinator/apps/commercetools/utils.py
- commerce_coordinator/apps/lms/tests/test_views.py
- commerce_coordinator/apps/lms/urls.py
- commerce_coordinator/apps/lms/views.py
- commerce_coordinator/settings/base.py
- commerce_coordinator/settings/local.py
- commerce_coordinator/urls.py
**Description**
This PR implements SONIC-302 and SONIC-256
> feat: [SONIC-302] Added order details page redirect view

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/constants.py
- commerce_coordinator/apps/commercetools/pipeline.py
- commerce_coordinator/apps/commercetools/tests/conftest.py
- commerce_coordinator/apps/commercetools/tests/raw_ct_order.json
- commerce_coordinator/apps/commercetools/tests/test_clients.py
- commerce_coordinator/apps/commercetools/tests/test_pipeline.py
- commerce_coordinator/apps/core/exceptions.py
- commerce_coordinator/apps/ecommerce/constants.py
- commerce_coordinator/apps/lms/filters.py
- commerce_coordinator/apps/rollout/tests/test_util_functions.py
- commerce_coordinator/apps/rollout/utils.py
- commerce_coordinator/settings/base.py
**Description**: Added Commerctools client and necessary functions to create refund/return for Commercetools order
**JIRA**: [SONIC-85](https://2u-internal.atlassian.net/browse/SONIC-85)
> feat: Added CT refund creation files

- commerce_coordinator/apps/commercetools/views.py
> fix: add JwtBearerAuthentication for commercetools OrderReturnedView

- commerce_coordinator/apps/commercetools/views.py
> feat: [SONIC-350] Added 'Order Refunded' Segment event

- commerce_coordinator/apps/lms/tasks.py
- commerce_coordinator/apps/lms/tests/constants.py
**Description**: Added order line item id to LMS enrollment attributes.
**JIRA**: [SONIC-332](https://2u-internal.atlassian.net/browse/SONIC-332)
> feat: Added order line item id to enrollment attributes

- commerce_coordinator/apps/commercetools/tests/test_views.py
- commerce_coordinator/apps/core/pipeline.py
- commerce_coordinator/apps/core/views.py
- commerce_coordinator/apps/frontend_app_ecommerce/tests/test_views.py
- commerce_coordinator/apps/frontend_app_ecommerce/views.py
- commerce_coordinator/apps/lms/tests/test_views.py
- commerce_coordinator/apps/lms/views.py
- Updated tests
- Added Debug pipeline stpe.
> fix: Using rest framework response in all areas we are able to

- commerce_coordinator/apps/commercetools/serializers.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/lms/signal_handlers.py
- commerce_coordinator/apps/lms/tasks.py
- commerce_coordinator/apps/lms/tests/constants.py
- commerce_coordinator/apps/lms/tests/test_signals.py
- commerce_coordinator/apps/lms/tests/test_tasks.py
**Description**: Added `order_id` to enrollment attributes object when fufilling an order through LMS client,
**JIRA**: [SONIC-457](https://2u-internal.atlassian.net/browse/SONIC-457)
> feat: Added 'order_id' to enrollment attributes

- commerce_coordinator/apps/lms/tests/test_views.py
- commerce_coordinator/apps/lms/views.py
**Description**: Changed value `order_line_id` to get the correct value from `enrollment_attributes`.
**JIRA**: [SONIC-483](https://2u-internal.atlassian.net/browse/SONIC-483)
> feat: Changed order_line_id to line_item_id

- commerce_coordinator/apps/commercetools/catalog_info/foundational_types.py
This is to support other LOBs and early release mistakes/bugs.
> fix: It has been decided that sanction shouldn't be final (lit: `[]`)

- commerce_coordinator/apps/commercetools/catalog_info/constants.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tests/raw_ct_order.json
- commerce_coordinator/apps/commercetools/tests/raw_ct_order_without_discount.json
- commerce_coordinator/apps/commercetools/utils.py
> fix: [SONIC-391] Added skipped properties for Segment event

- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/settings/base.py
> fix: Order refunded email should show human readable order number

- commerce_coordinator/apps/commercetools/pipeline.py
https://app.datadoghq.com/apm/trace/664df8e30000000083b51ed1116166f5?colorBy=service&env=prod&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=979724094728285240&spanViewType=errors&timeHint=1716386019699.474&view=spans
> fix: ValueError in CT Unified Order History Pipeline

- commerce_coordinator/settings/base.py
- commerce_coordinator/urls.py
health now optionally needs a slash
> fix: Adding favicon.ico, Root paths and fixing health 

- .coveragerc
- .github/workflows/ci.yml
- .github/workflows/coverage.yml
Based off of: https://github.com/openedx/openedx-events/pull/323/files
> build: replace codecov with python-coverage-comment-action

- commerce_coordinator/settings/base.py
Added signal configs for previous work: https://github.com/edx/commerce-coordinator/pull/234
> fix: Added refund signal config

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/tests/test_clients.py
- commerce_coordinator/apps/commercetools/utils.py
> fix: [SONIC-241] Generalize CT exception logging

- docs/decisions/0008-pull-commerce-coordinator-code-out-of-platform.rst
> docs: add ADR for pulling cc code out of platform

- commerce_coordinator/apps/lms/tests/test_views.py
- commerce_coordinator/apps/lms/views.py
> feat: redirect program purchases to legacy from lms/redirect

- commerce_coordinator/apps/lms/views.py
> fix: fix query params for redirect url

- commerce_coordinator/apps/commercetools/management/commands/find_ct_dulplicate_purchases.py
- commerce_coordinator/apps/commercetools/management/commands/find_ct_duplicate_purchases.py
> feat: add ct duplicates management command

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/pipeline.py
- commerce_coordinator/apps/ecommerce/clients.py
- commerce_coordinator/apps/ecommerce/pipeline.py
- commerce_coordinator/apps/frontend_app_ecommerce/views.py
> refactor: remove logs from order history API

- commerce_coordinator/apps/core/admin.py
Reverts edx/commerce-coordinator#322
> Revert "temp: add lms_user_id to django admin"

- .github/workflows/upgrade-python-requirements.yml
> refactor: used openedx workflow of requirements upgrade instead of edx one

- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- use dynamic lob property
Relevant JIRA Ticket: [SONIC-606](https://2u-internal.atlassian.net/browse/SONIC-606)
> SONIC-606: Fetch LOB property dynamically from product attributes

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/lms/views.py
- commerce_coordinator/apps/rollout/pipeline.py
- commerce_coordinator/apps/rollout/waffle.py
Reverts edx/commerce-coordinator#326
> Revert "fix: update payment page redirect for program"

- commerce_coordinator/apps/lms/serializers.py
- commerce_coordinator/apps/lms/tests/test_utils.py
- commerce_coordinator/apps/lms/tests/test_views.py
- commerce_coordinator/apps/lms/utils.py
- commerce_coordinator/apps/lms/views.py
Ticket
[SONIC-866](https://2u-internal.atlassian.net/browse/SONIC-866)
> feat: Part of Program refund in Commerce Coordinator

- commerce_coordinator/apps/frontend_app_ecommerce/views.py
> chore: add more logging to OH endpoint

- README.rst
- commerce_coordinator/apps/commercetools/catalog_info/utils.py
- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/signals.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tasks.py
- commerce_coordinator/apps/commercetools/tests/catalog_info/test_utils.py
- commerce_coordinator/apps/commercetools/tests/raw_ct_order.json
- commerce_coordinator/apps/commercetools/tests/sub_messages/test_tasks.py
- commerce_coordinator/apps/commercetools/tests/test_clients.py
- commerce_coordinator/apps/commercetools/tests/test_signals.py
- commerce_coordinator/apps/lms/clients.py
- commerce_coordinator/apps/lms/signal_handlers.py
- commerce_coordinator/apps/lms/signals.py
- commerce_coordinator/apps/lms/tasks.py
- commerce_coordinator/apps/lms/tests/constants.py
- commerce_coordinator/apps/lms/tests/test_clients.py
- commerce_coordinator/apps/lms/tests/test_signals.py
- commerce_coordinator/apps/lms/tests/test_tasks.py
- commerce_coordinator/settings/base.py
- commerce_coordinator/settings/test.py
- fix readme formatting
- fulfill entitlements
Relevant JIRA Ticket: [SONIC-861](https://2u-internal.atlassian.net/browse/SONIC-861)
> SONIC-861: Fulfillment of program order

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/tests/conftest.py
- commerce_coordinator/apps/commercetools/tests/raw_ct_program.json
- commerce_coordinator/apps/commercetools/tests/test_clients.py
- commerce_coordinator/apps/lms/tests/test_views.py
- commerce_coordinator/apps/lms/views.py
- commerce_coordinator/apps/rollout/pipeline.py
- commerce_coordinator/apps/rollout/tests/test_pipeline.py
- commerce_coordinator/apps/rollout/waffle.py
> fix: update payment page redirect for program

- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tests/test_utils.py
- commerce_coordinator/apps/commercetools/utils.py
Pass correct price to Order confirmation email
> Fix Order confirmation email for bundle purchase

- .github/workflows/commitlint.yml
- commerce_coordinator/settings/utils.py
Formate logging strings for DD logs
[SONIC-897](https://2u-internal.atlassian.net/browse/SONIC-879)
> fix: format logging string

- commerce_coordinator/settings/utils.py
Reverts edx/commerce-coordinator#344
> Revert "fix: format logging string"

- commerce_coordinator/apps/commercetools/constants.py
- commerce_coordinator/apps/commercetools/serializers.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tests/test_utils.py
- commerce_coordinator/apps/commercetools/utils.py
- commerce_coordinator/apps/lms/signal_handlers.py
- commerce_coordinator/apps/lms/tasks.py
- commerce_coordinator/apps/lms/tests/constants.py
- commerce_coordinator/apps/lms/tests/test_signals.py
- commerce_coordinator/apps/lms/tests/test_tasks.py
Send Entitlement Fulfillment Failure Email
> feat: send entitlement fulfillment failure email

- commerce_coordinator/apps/commercetools/constants.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
> fix: edx_course_entitlement mapping and product_type for events

- commerce_coordinator/apps/commercetools/catalog_info/utils.py
- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/signals.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tasks.py
- commerce_coordinator/apps/commercetools/tests/catalog_info/test_utils.py
- commerce_coordinator/apps/commercetools/tests/constants.py
- commerce_coordinator/apps/commercetools/tests/raw_ct_order.json
- commerce_coordinator/apps/commercetools/tests/sub_messages/test_tasks.py
- commerce_coordinator/apps/commercetools/tests/test_clients.py
- commerce_coordinator/apps/commercetools/tests/test_signals.py
- commerce_coordinator/apps/commercetools/tests/test_tasks.py
- commerce_coordinator/apps/core/tasks.py
- commerce_coordinator/apps/lms/clients.py
- commerce_coordinator/apps/lms/signals.py
- commerce_coordinator/apps/lms/tasks.py
- commerce_coordinator/apps/lms/tests/test_clients.py
- commerce_coordinator/apps/rollout/pipeline.py
- commerce_coordinator/settings/base.py
- commerce_coordinator/settings/test.py
- resolve concurrency issue in fulfillment
Relevant JIRA Ticket: [SONIC-826](https://2u-internal.atlassian.net/browse/SONIC-826)
> SONIC-826: Concurrency issue while updating line items after fulfillment

- commerce_coordinator/settings/utils.py
Update logging config for DD logs
> fix: format logging for DD logs

- commerce_coordinator/settings/utils.py
Reverts edx/commerce-coordinator#350
> Revert "fix: format logging for DD logs"

- commerce_coordinator/apps/commercetools/tests/test_utils.py
- commerce_coordinator/apps/commercetools/utils.py
Handle product-level discount 
[SONIC-897](https://2u-internal.atlassian.net/browse/SONIC-897)
> fix: handle product level discount

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/pipeline.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tests/sub_messages/test_tasks.py
- commerce_coordinator/apps/commercetools/tests/test_pipeline.py
- commerce_coordinator/apps/commercetools/tests/test_utils.py
- commerce_coordinator/apps/commercetools/utils.py
- commerce_coordinator/apps/lms/tests/test_views.py
- commerce_coordinator/apps/lms/views.py
- commerce_coordinator/apps/paypal/pipeline.py
- commerce_coordinator/apps/stripe/pipeline.py
Ticket
[Handle InvalidFilterType exception, Missing Transaction ID and Incorrect Title in refund flow](https://2u-internal.atlassian.net/browse/SONIC-936)
> fix: fixed InvalidFilterType exception, Missing Transaction ID and Incorrect Title in refund flow

- commerce_coordinator/apps/commercetools/catalog_info/constants.py
- commerce_coordinator/apps/commercetools/catalog_info/foundational_types.py
- commerce_coordinator/apps/commercetools/management/commands/_utils.py
- commerce_coordinator/apps/commercetools/management/commands/create_bundle_specific_custom_fields.py
- commerce_coordinator/apps/commercetools/management/commands/create_discount_specific_custom_fields.py
Ticket:
[Add custom fields for discounts](https://2u-internal.atlassian.net/browse/SONIC-887)
> feat: implemented command to add custom fields for discounts

- commerce_coordinator/apps/commercetools/catalog_info/constants.py
[[Prod] Add custom fields for discounts](https://2u-internal.atlassian.net/browse/SONIC-888)
> refactor: updated cart discount custom fields for prod

- commerce_coordinator/settings/utils.py
> fix: fix DD log stream

- .github/workflows/check-reserved-keywords.yml
- .github/workflows/ci2.yml
- .github/workflows/pypi-publish.yml
- commerce_coordinator/apps/commercetools/catalog_info/constants.py
- commerce_coordinator/apps/commercetools/catalog_info/foundational_types.py
- commerce_coordinator/apps/commercetools/management/commands/_utils.py
- commerce_coordinator/apps/commercetools/management/commands/update_discount_specific_custom_fields.py
[Update the category custom field and create a channel custom field in the cart discount](https://2u-internal.atlassian.net/browse/SONIC-965)
> feat: added management command to handle discount code category enum updates and added channel category

- commerce_coordinator/apps/commercetools/serializers.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/lms/signal_handlers.py
- commerce_coordinator/apps/lms/tasks.py
- commerce_coordinator/apps/lms/tests/constants.py
- commerce_coordinator/apps/lms/tests/test_signals.py
- commerce_coordinator/apps/lms/tests/test_tasks.py
fallback for user first name empty
> fix: fallback for user first name empty

- commerce_coordinator/apps/commercetools/http_api_client.py
- commerce_coordinator/apps/commercetools/tests/test_http_api_client.py
- commerce_coordinator/apps/lms/views.py
Improvements:
- Uses product projects api instead of projects api because its optimized by ct. https://docs.commercetools.com/foundry/best-practice-guides/product-discovery
- increases retries
- puts performance/time taken logs
- improved logs
> fix: improve program price api

- commerce_coordinator/apps/commercetools/data.py
Fix the order history breaking page due to discount objects missing in the order.
[SONIC-980](https://2u-internal.atlassian.net/browse/SONIC-980)
> fix: fix order history discount null case

- commerce_coordinator/apps/commercetools/catalog_info/constants.py
- commerce_coordinator/apps/commercetools/catalog_info/foundational_types.py
- commerce_coordinator/apps/commercetools/management/commands/create_mobile_specific_custom_fields.py
- commerce_coordinator/apps/commercetools/tests/test_clients.py
[Add Custom Field for Mobile Purchase orders](https://2u-internal.atlassian.net/browse/SONIC-1018)
> feat: added management command to add mobile specific custom fields

- commerce_coordinator/apps/commercetools/tests/constants.py
- commerce_coordinator/apps/commercetools/tests/test_views.py
- commerce_coordinator/apps/commercetools/urls.py
- commerce_coordinator/apps/commercetools/views.py
> feat: add new endpoints for mobile product sync

- commerce_coordinator/apps/order_fulfillment/urls.py
- commerce_coordinator/apps/order_fulfillment/views.py
> fix: update fulfillment webhook response endpoint

- commerce_coordinator/apps/commercetools/tests/test_views.py
- commerce_coordinator/apps/commercetools/urls.py
- commerce_coordinator/apps/commercetools/views.py
> feat: add new api url for product create event

- .github/workflows/check-reserved-keywords.yml
- .github/workflows/ci2.yml
> fix: upgrade versions in cc ci file

- commerce_coordinator/apps/commercetools/data.py
- commerce_coordinator/apps/commercetools/tests/raw_ct_order.json
- commerce_coordinator/apps/commercetools/tests/raw_ct_order_without_discount.json
- commerce_coordinator/apps/commercetools/tests/test_views.py
- commerce_coordinator/apps/ecommerce/data.py
> fix: add mobile order field in order object

- .github/workflows/ci2.yml
- commerce_coordinator/apps/commercetools/tests/test_clients.py
> fix: remove tox cache removal

- commerce_coordinator/apps/lms/views.py
Fix the negative discount value for the program price info API
> fix: fix negative program discount value

- commerce_coordinator/apps/commercetools/data.py
> fix: add payment processor in order history response

- commerce_coordinator/apps/commercetools/clients.py
- use normalized payment key for android payment
> fix: use normalized payment key for android payment

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/tests/test_clients.py
- commerce_coordinator/apps/iap/google_validator.py
- commerce_coordinator/apps/iap/ios_validator.py
- commerce_coordinator/apps/iap/payment_processor.py
- commerce_coordinator/apps/iap/tests/test_google_validator.py
- commerce_coordinator/apps/iap/tests/test_ios_validator.py
- commerce_coordinator/apps/iap/tests/test_payment_processor.py
- commerce_coordinator/apps/iap/tests/test_utils.py
- commerce_coordinator/apps/iap/tests/test_views.py
- commerce_coordinator/apps/iap/utils.py
- commerce_coordinator/apps/iap/views.py
- commerce_coordinator/settings/base.py
- commerce_coordinator/settings/local.py
- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
This work is related to validating purchase tokens for iOS and Android.
> feat: fetching mobile purchase details with validation

- commerce_coordinator/apps/commercetools/catalog_info/utils.py
- commerce_coordinator/apps/commercetools/signals.py
- commerce_coordinator/apps/commercetools/tasks.py
- commerce_coordinator/apps/commercetools/tests/constants.py
- commerce_coordinator/apps/commercetools/tests/test_signals.py
- commerce_coordinator/apps/commercetools/tests/test_tasks.py
- commerce_coordinator/apps/commercetools/utils.py
- commerce_coordinator/apps/paypal/views.py
- commerce_coordinator/apps/stripe/tests/test_views.py
- commerce_coordinator/apps/stripe/views.py
> fix: Send refund email for PSP first approach

- docs/decisions/arch-diagrams/andriod-refund-flow.mmd
- docs/decisions/arch-diagrams/ios-refund-flow.mmd
- docs/decisions/arch-diagrams/mobile-create-order.mmd
- docs/decisions/arch-diagrams/mobile-ecomm-architecture.mmd
> feat: architecture diagram for Mobile Ecommerce flows to CT.

- commerce_coordinator/apps/iap/views.py
> fix: fix payment method name

- commerce_coordinator/apps/commercetools/catalog_info/edx_utils.py
> fix: image url destructuring

- commerce_coordinator/apps/iap/segment_events.py
- commerce_coordinator/apps/iap/tests/test_segment_events.py
- fix tax value in mobile order completed event
> fix: fix tax value in mobile order completed event

- commerce_coordinator/apps/commercetools/serializers.py
> fix: fixed provider ID blank issue

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/tests/test_clients.py
- commerce_coordinator/apps/lms/tests/test_views.py
- commerce_coordinator/apps/lms/urls.py
- commerce_coordinator/apps/lms/views.py
Adds an endpoint to add credit courses to commercetools checkout
> feat: add credit checkout endpoint

- commerce_coordinator/apps/lms/views.py
Minor error log improvement for DD alert
> feat: CreditCheckoutView Error log improvement

- commerce_coordinator/apps/rollout/pipeline.py
- commerce_coordinator/apps/rollout/tests/test_pipeline.py
Fix Payment Page redirect try catch and improve quality
> fix: fix Payment Page redirect try catch and improve logging

- commerce_coordinator/apps/commercetools/tasks.py
> fix: task logger

- commerce_coordinator/apps/commercetools/pipeline.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tasks.py
- commerce_coordinator/apps/commercetools/tests/test_pipeline.py
- commerce_coordinator/apps/commercetools/utils.py
- commerce_coordinator/apps/paypal/pipeline.py
- commerce_coordinator/apps/stripe/pipeline.py
- fix refund amount in paypal and stripe refund events
Relevant JIRA Ticket: [SONIC-1133](https://2u-internal.atlassian.net/browse/SONIC-1133)
> SONIC-1133: Fix refund amount in refund email for PSP

- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tests/sub_messages/test_tasks.py
- fix refund amount in edges cases
Relevant JIRA Ticket: [SONIC-1133](https://2u-internal.atlassian.net/browse/SONIC-1133)
> SONIC-1133: fix refund amount in edges cases

- commerce_coordinator/apps/commercetools/tasks.py
- commerce_coordinator/apps/commercetools/tests/test_tasks.py
- commerce_coordinator/apps/iap/views.py
- fix IAP logs for DD monitoring
> fix: fix IAP logs for DD monitoring

- commerce_coordinator/apps/iap/payment_processor.py
- commerce_coordinator/apps/iap/tests/test_views.py
- commerce_coordinator/apps/iap/views.py
- improve iap log
- add temp log for debug
> fix: improve iap log

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/tasks.py
- commerce_coordinator/apps/order_fulfillment/clients.py
> fix: add retry on ct update line item

- commerce_coordinator/apps/iap/payment_processor.py
- commerce_coordinator/apps/iap/tests/test_payment_processor.py
- commerce_coordinator/apps/iap/utils.py
- commerce_coordinator/apps/lms/urls.py
- commerce_coordinator/apps/lms/views.py
- commerce_coordinator/settings/base.py
- commerce_coordinator/templates/sdn_failure.html
> feat: Added SDN failure Django view and handled mobile receipt error response
