- docs/decisions/0003-internal-communication.rst
**Description:** Adding a new ADR to codify use of Django Signals as a default internal communication mechanism and Django Apps as the recommended way to extend Commerce Coordinator functionality. This explicitly leaves out example code and API documentation in favor of adding those into official docs as they are built.
**JIRA:** REV-2405
> docs: ADR-3 - Internal Communication

- docs/decisions/0003-internal-communication.rst
The results of the Primer are adequately covered by the ADR, so removing the reference as the doc is not publicly accessible.
> docs: Removed internal doc reference

- Makefile
**Description:** If/when we start publishing Docker images, we should use the actual repo name
**JIRA:** [[ARCHBOM-1963] IDA Cookiecutter: some Makefile targets do not substitute repo_name - JIRA](https://openedx.atlassian.net/browse/ARCHBOM-1963)
> fix!: Replaced placeholder with the repo name

- .gitignore
Since my earlier update to the README specifies using venv for the virtual environment, I'm adding .venv to the gitignore file so nobody accidentally commits their virtual environment
> fix: add venv files to gitignore

- README.rst
Using redis/celery is needed for the commerce-coordinator to do anything, so I've moved those steps out of the 'Local testing with celery' section and up into the initial setup/running of the code
Note: known CI checks failing (confirmed they have the current 'expected' errors): 
- docs check has known failure (REV-2615)
- quality check has known failure, fix on the way from Ben:  https://github.com/edx/commerce-coordinator/pull/10
> fix: move redis setup/starting into regular steps

- setup.py
[ARCHBOM-1772](https://openedx.atlassian.net/browse/ARCHBOM-1772)
Update setup.py to use constraint files when generating requirements files for packaging and distribution.
PR generated automatically with Jenkins job cleanup-python-code. 
Result of running `python setup.py bdist_wheel` before applying fix (in .egg-info/requires.txt)\: 
edx-auth-backends
djangorestframework
mysqlclient
pytz
django-cors-headers
django-waffle
edx-django-utils
edx-drf-extensions
django-extensions
Django>=2.2
django-rest-swagger
edx-rest-api-client
edx-django-release-util
Result of running `python setup.py bdist_wheel` after applying fix (in .egg-info/requires.txt)\: 
Django>=2.2
django-cors-headers
django-extensions
django-rest-swagger
django-waffle
djangorestframework
edx-auth-backends …
> feat: advertise constraints in setup.py

- Makefile
Fill in placeholder `repo_name` in Makefile to get Docker pushes working.
* Jira: [REV-2564](https://openedx.atlassian.net/browse/REV-2564)
* Research: [Confluence](https://openedx.atlassian.net/wiki/spaces/~931919476/pages/3342762040/REV-2564)
> fix: [REV-2564] s/repo_name/commerce-coordinator for github_docker_* Makefile directives

- README.rst
The celery testing steps in the README: 
-  still said 'lms' instead of 'demo_lms' (app was renamed [here](https://github.com/edx/commerce-coordinator/pull/12), but I missed this spot in the README)
- duplicated the test_celery_signal_task test
This PR fixes those two things. 
Note: it's known that the 'docs' check fails in this repo until we fix [REV-2615](https://openedx.atlassian.net/browse/REV-2615)
> README: Clean up celery testing section (demo_lms name and duplicated step)

- commerce_coordinator/settings/production.py
ArgoCD errors with:
```
File "/edx/app/commerce-coordinator/commerce_coordinator/settings/production.py", line 28, in <module>
config_from_yaml = yaml.load(f)
TypeError: load() missing 1 required positional argument: 'Loader'
```
This is because `yaml.load(f)` now requires a new parameter, or the use of `safe_load()`. See https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation.
Solution copied from [Confluence](https://openedx.atlassian.net/wiki/spaces/SRE/pages/3298296133/Creating+a+New+Kubernetes+Django+Service#Some-notes-on-various-boilerplate-files).
Successfully loaded project using `safe_load()` in ArgoCD development environment.
* Jira: [REV-2564](https://openedx.atlassian.net/browse/REV-2564)
* Research: [Confluence](https://openedx.atlassian.net/wiki/spaces/~931919 …
> fix: [REV-2564] deprecated yaml.load(); use safe_load()

- README.rst
- commerce_coordinator/apps/orders/admin.py
- commerce_coordinator/apps/orders/apps.py
- commerce_coordinator/apps/orders/clients.py
- commerce_coordinator/apps/orders/models.py
- commerce_coordinator/apps/orders/tests.py
- commerce_coordinator/apps/orders/urls.py
- commerce_coordinator/apps/orders/views.py
- commerce_coordinator/settings/base.py
- commerce_coordinator/settings/local.py
- commerce_coordinator/urls.py
- local-provision-commerce-coordinator.sh
- provision-commerce-coordinator.sh
**Description:** Add an orders app that'll be used for communication around order retrieval. The first endpoint will be to request order information for a user, but in the future we'll add another (or modify this one) to be able to call an external provider for a user's orders. 
**JIRA:** [Link to JIRA ticket](https://openedx.atlassian.net/browse/REV-2575)
**Installation instructions:** 
- follow the setup steps in the commerce-coordinator README file [here](https://github.com/edx/commerce-coordinator)
- run commerce-coordinator locally
Test the endpoint: with this branch, go to the new endpoint test page, specifying a user that has orders in your local environment: http://localhost:8140/orders/order_history/?username=edx&page=1&page_size=20
Test via order …
> REV-2575: add orders app with endpoint to retrieve order info from ecommerce

- commerce_coordinator/urls.py
- docs/commerce_coordinator.apps.api.rst
- docs/commerce_coordinator.apps.api.tests.rst
- docs/commerce_coordinator.apps.api.v1.rst
- docs/commerce_coordinator.apps.api.v1.tests.rst
- docs/commerce_coordinator.apps.core.migrations.rst
- docs/commerce_coordinator.apps.core.rst
- docs/commerce_coordinator.apps.core.tests.rst
- docs/commerce_coordinator.apps.demo_lms.migrations.rst
- docs/commerce_coordinator.apps.demo_lms.rst
- docs/commerce_coordinator.apps.orders.migrations.rst
- docs/commerce_coordinator.apps.orders.rst
- docs/commerce_coordinator.apps.rst
- docs/commerce_coordinator.rst
- docs/commerce_coordinator.settings.rst
- docs/conf.py
- docs/modules.rst
- tox.ini
This PR fixes 2 errors in the build process:
The docs GitHub action is currently failing due to an error like:
```
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```
This PR fixes that error by running `django.setup()` to bootstrap all the classes required so the automatic documentation tool `autodoc` can do its job.
After that error is fixed, the GitHub action fails due to an error like:
```
docs run-test: commands[5] | python setup.py check --restructuredtext --strict
...
warning: check: Duplicate implicit target name: "...".
...
ERROR: InvocationError for command /home/runner/work/commerce-coordinator/commerce-coordinator/.tox/docs/bin/python setup.py check --restructuredtext --strict (exited with code 1)
```
This docs test lints all rST in the repository (as …
> docs: setup django for sphynx & bypass deprecated rST check

- Dockerfile
- commerce_coordinator/settings/base.py
Work in commerce-coordinator was blocked because of missing commits from edx-cookiecutter.
Review other commits to edx-cookiecutter since commerce-coordinatore repo creation using `git log --patch --stat --reverse --oneline --no-merges --invert-grep --since="2021-10-01" --grep "^chore:"`
Found and applied https://github.com/openedx/edx-cookiecutters/commit/8dfdeec9b84e71cc5255bc4f6e1dbceb1e7750d7 and https://github.com/openedx/edx-cookiecutters/commit/912c5ff10492bee055b9ad4d50d9cad649b4a1fc.
* On dev:
> chore: merge updates from edx-cookiecutter

- commerce_coordinator/settings/base.py
RequestMetricsMiddleware has been renamed to RequestCustomAttributesMiddleware.
This PR squashes this warning:
.virtualenvs/cc/lib/python3.8/site-packages/edx_rest_framework_extensions/middleware.py:198: DeprecationWarning: Use 'RequestCustomAttributesMiddleware' in place of 'RequestMetricsMiddleware'.
* See: [edx-drf-extensions docs](https://edx-drf-extensions.readthedocs.io/en/7.0.1/middleware.html#edx_rest_framework_extensions.middleware.RequestMetricsMiddleware)
> fix: update RequestMetricsMiddleware to RequestCustomAttributesMiddleware

- Makefile
Since New Relic is an non-Open-edX-specific thing, we have moved to injecting it in our internal Dockerfile repos.
This PR removes recipes for generating New Relic Docker builds from the commerce-coordinator Makefile rules, which I neglected to do in a previous PR.
This PR affects recipes in Makefile rules:
* docker_build
* travis_docker_tag
* travis_docker_auth
* github_docker_build
* github_docker_tag
* github_docker_push
I think we have shifted from supporting Travis CI to GitHub Actions.
This PR proposes to remove Travis-related files and code from commerce-coordinator's Makefile.
* History: I previously removed New Relic from:
* edx-cookiecutter Dockerfile in https://github.com/openedx/edx-cookiecutters/pull/173
* commerce-coordinator Dockerfile in …
> fix: remove New Relic from Makefile & deprecate Travis

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/production.in
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
Per the [Django 3.2 docs](https://docs.djangoproject.com/en/3.2/topics/cache/#memcached):
> The MemcachedCache backend is deprecated as python-memcached has some problems and seems to be unmaintained. Use PyMemcacheCache or PyLibMCCache instead.
This PR replaces `python-memcached` with `pymemcache` in requirements/production.in.
* See also: [edx-internal#6827](https://github.com/edx/edx-internal/pull/6827/files#diff-a44b696bee0711fbaeb892add35abf3d93ac3ed179d56c17320b7bddf624e460R36), which adds the following to Django settings in production:
```
CACHES:
default:
BACKEND: django.core.cache.backends.memcached.PyMemcacheCache
KEY_PREFIX: commerce-coordinator
LOCATION:
- <host>:<port>
- <host>:<port>
```
> feat: use PyMemcacheCache caching backend in production

- commerce_coordinator/settings/base.py
This PR adds Django application `edx_django_utils.user` to the `INSTALLED_APPS` so that commerce-coordinator supports more robust, programmatic user management.
In particular, the `edx_django_utils.user` app allows tools like app-permissions to manage Django users and groups in commerce-coordinator.
This is required so tools can programmatically manage the users and groups that can, e.g. access the Django admin dashboard in commerce-coordinator.
* Confluence: [Instructions](https://2u-internal.atlassian.net/wiki/spaces/SRE/pages/19237986/How+To+Onboard+a+Django+Service+to+App+Permissions)
Tested locally by running `python manage.py` and verifying the addition of management commands:
```
[user]
manage_group
manage_user
```
> feat: add django app edx_django_utils.user for app-permissions

- commerce_coordinator/apps/core/signal_helpers.py
- commerce_coordinator/apps/demo_lms/views.py
- commerce_coordinator/apps/ecommerce/apps.py
- commerce_coordinator/apps/ecommerce/signals.py
- commerce_coordinator/apps/ecommerce/urls.py
- commerce_coordinator/apps/ecommerce/views.py
- commerce_coordinator/apps/frontend_app_ecommerce/apps.py
- commerce_coordinator/apps/titan/apps.py
- commerce_coordinator/apps/titan/signals.py
- commerce_coordinator/apps/titan/tasks.py
- commerce_coordinator/settings/base.py
- commerce_coordinator/urls.py
We are doing an internal hackathon for some rapid prototyping in the Coordinator. The objective of this hackathon is to get proof of concept code for redeeming enrollment codes (aka 100% coupons) via an existing ecommerce system in our company called Titan.
This PR adds:
* An incoming external connection through a new Coordinator API resource at `/ecommerce/redeem_enrollment_code`
* A internal connection through a new signal called `enrollment_code_redemption_requested_signal` and its receiver `enrollment_code_redemption_requested_create_order`
* A Celery task called `enrollment_code_redemption_requested_create_order_task` that will in the future call the Titan `/redeemEnrollmentCode` endpoint in a future PR in this repo.
* Jira: …
> feat: [REV-2847] add ecommerce/redeem_enrollment_code incoming connection & signals

- Makefile
**Description:** We are adding the commerce coordinator to sandbox builds and Ansible task uses this Makefile target to install production requirements https://github.com/openedx/configuration/blob/1162f70ebf94c1af4b096476df2cecd234091671/playbooks/roles/edx_django_service/tasks/main.yml#L164
**JIRA:** https://2u-internal.atlassian.net/jira/software/c/projects/PSRE/boards/655?modal=detail&selectedIssue=PSRE-1830
**Reviewers:**
finished.
> fix: production requirements Makefile target

- .gitignore
- README.rst
- commerce_coordinator/apps/core/clients.py
- commerce_coordinator/apps/ecommerce/clients.py
- commerce_coordinator/apps/ecommerce/pipeline.py
- commerce_coordinator/apps/ecommerce/signals.py
- commerce_coordinator/apps/ecommerce/tests/__init__.py
- commerce_coordinator/apps/ecommerce/tests/test_clients.py
- commerce_coordinator/apps/ecommerce/views.py
- commerce_coordinator/apps/frontend_app_ecommerce/tests/__init__.py
- commerce_coordinator/apps/frontend_app_ecommerce/tests/test_filters.py
- commerce_coordinator/apps/frontend_app_ecommerce/tests/test_views.py
- commerce_coordinator/apps/titan/clients.py
- commerce_coordinator/apps/titan/signals.py
- commerce_coordinator/apps/titan/tasks.py
- commerce_coordinator/celery_app.py
- commerce_coordinator/settings/base.py
- commerce_coordinator/settings/devstack.py
- commerce_coordinator/settings/local.py
- docs/commerce_coordinator.apps.core.rst
- docs/commerce_coordinator.apps.ecommerce.rst
- docs/commerce_coordinator.apps.frontend_app_ecommerce.migrations.rst
- docs/commerce_coordinator.apps.frontend_app_ecommerce.rst
- docs/commerce_coordinator.apps.frontend_app_ecommerce.tests.rst
- docs/commerce_coordinator.apps.rst
- docs/commerce_coordinator.apps.titan.rst
- docs/commerce_coordinator.apps.titan.tests.rst
We are doing an internal hackathon for some rapid prototyping in the Coordinator. The objective of this hackathon is to get proof of concept code for redeeming enrollment codes (aka 100% coupons) via an existing ecommerce system in our company called Titan.
This PR adds:
* Two API clients for Titan, one using OAuth (`TitanOAuthAPIClient`) and another using only an API key (`TitanAPIClient`).
* Wiring to the Celery task `enrollment_code_redemption_requested_create_order_task` to call the Titan `/redeemEnrollmentCode` endpoint using `TitanAPIClient`.
* A new Celery task called `enrollment_code_redemption_requested_create_order_oauth_task` that calls the Titan `/redeemEnrollmentCode` endpoint using `TitanOAuthAPIClient`.
This PR also:
* Renames a couple of parameters from …
> feat: [REV-2847] add TitanAPIClient and TitanOAuthAPIClient

- Makefile
- README.rst
- commerce_coordinator/settings/devstack.py
- docker-compose.yml
- find-start-lms.sh
- provision-commerce-coordinator.sh
- `provision-commerce-coordinator.sh` now creates the full Docker stack.
- `docker-compose.yml` modified to support devstack and titan networks.
- `commerce_coordinator/settings/devstack.py` now points to the default instance name for the titan application (though im unsure if the path is correct), can be configured via EnvVar
- `Makefile` changes for provisioning as well as manual orchestration of the 3 stacks.
> Updates for Docker Provisioning, And first attempt at Titan support

- .github/workflows/codeql-analysis.yml
Adds CodeQL to commerce-coordinator using GitHub default template.
Scans by default all PRs & commits to develop and main, along with once weekly on a schedule.
> feat: add codeql

- .github/workflows/upgrade-python-requirements.yml
The GitHub Action job in upgrade-python-requirements.yml automatically generates Python requirements upgrade PRs.
This PR adds this job to commerce-coordinator, configuring so that
* Job is run monthly on the 1st of the month
* Both develop & main branches receive PRs by default (a necessary evil right now, I think)
* PRs tag @edx-revenue-tasks so the PR review requests creates a Jira ticket on the maintainer's board
* Errors are sent to revenue-tasks@edx.org, which creates a Jira ticket on the maintainer's board
An alternative option would be to set `send_success_notification` to true and not use @edx-revenue-tasks as a `user_reviewers`. However, that would make the created task for a successful run (which requires the followup action of a review) look very similar to a failed PR (which …
> feat: add upgrade-python-requirements.yml GitHub Action

- commerce_coordinator/settings/local.py
ALLOWED_HOSTS is a Django setting for valid hostnames your app may be aliased as.
host.docker.internal is an internal Docker alias for the host machine running Docker Desktop. (localhost from within a Docker container is the container itself, not the machine running Docker Desktop.)
We are currently using host.docker.internal to reach Coordinator from devstack ecommerce.
Thus, requests arriving to localhost Coordinator may have originally been sent to host.docker.internal:8130 instead of localhost:8130.
This configuration makes Django not reject requests originating from Docker containers with destination to localhost.
* Jira: [THES-130](https://2u-internal.atlassian.net/browse/THES-130) Coordinator throws error when Titan calls /fulfill
* Related PR: …
> build: add host.docker.internal to ALLOWED_HOSTS

- commerce_coordinator/apps/core/clients.py
- commerce_coordinator/apps/core/serializers.py
- commerce_coordinator/apps/core/signal_helpers.py
- commerce_coordinator/apps/core/tests/test_clients.py
- commerce_coordinator/apps/core/tests/test_serializers.py
- commerce_coordinator/apps/core/tests/test_signal_helpers.py
- commerce_coordinator/apps/ecommerce/clients.py
- commerce_coordinator/apps/lms/clients.py
- commerce_coordinator/apps/lms/signals.py
- commerce_coordinator/apps/lms/tasks.py
- commerce_coordinator/apps/titan/clients.py
- commerce_coordinator/apps/titan/serializers.py
- commerce_coordinator/apps/titan/signals.py
- commerce_coordinator/apps/titan/tasks.py
- commerce_coordinator/apps/titan/tests/test_clients.py
- commerce_coordinator/apps/titan/tests/test_tasks.py
- commerce_coordinator/apps/titan/views.py
- commerce_coordinator/settings/base.py
- commerce_coordinator/settings/devstack.py
- commerce_coordinator/settings/local.py
This PR adds a POST call to https://courses.edx.org/api/enrollment/v1/enrollment on call of signal `commerce_coordinator.apps.lms.signals.fulfill_order_placed_send_enroll_in_course`.
This allows other systems to enroll a user in a course.
The implementation looks like this:
```mermaid
flowchart TB
subgraph Fulfillment
direction TB
commerce_coordinator.apps.lms.clients.LmsAPIClient.enroll_user_in_course --> commerce_coordinator.apps.lms.clients.https://courses.edx.org/api/enrollment/v1/enrollment::POST
commerce_coordinator.apps.lms.signals.fulfill_order_placed_send_enroll_in_course --> commerce_coordinator.apps.lms.tasks.fulfill_order_placed_send_enroll_in_course_task
commerce_coordinator.apps.lms.tasks.fulfill_order_placed_send_enroll_in_course_task --> …
```
> feat: Add call to LMS Enrollment API

- commerce_coordinator/apps/stripe/clients.py
- commerce_coordinator/apps/stripe/tests/test_clients.py
* Jira: [THES-187](https://2u-internal.atlassian.net/browse/THES-187) Create Draft Payment - Step 2 - Create clients.StripeAPIClient.create_or_get_payment_intent in Coordinator stripe app
> fix: add ValueError on bad args to StripeAPIClient.create_payment_intent

- commerce_coordinator/apps/stripe/clients.py
- commerce_coordinator/apps/stripe/tests/test_clients.py
Adds `retrieve_payment_intent`, which calls the Stripe PaymentIntent Retrieve API endpoint [[docs](https://stripe.com/docs/api/payment_intents/retrieve)].
We will need this call to return the `clientSecret` whenever Titan replies with a GET request:
```mermaid
sequenceDiagram
participant P as Payment MFE
participant C as Coordinator
participant T as Titan
participant S as Stripe
P->>+C: Create or Get Draft Payment
C-->>-P: (response)
C->>+T: Get Active Order
T-->>-C: (response)
alt Active, unpaid payment found from Titan
rect rgb(255, 245, 173, .25)
note over T: New:
C->>+S: Get Draft Payment
S-->>-C: (response)
end
C-->>P: (response with payment_number and order_uuid)
end
```
We can't store the `clientSecret` in Titan because that's prohibited by PCI: [[Stripe …
> feat: new stripe.clients.StripeAPIClient.retrieve_payment_intent

- commerce_coordinator/apps/stripe/clients.py
- commerce_coordinator/apps/stripe/pipeline.py
- commerce_coordinator/apps/stripe/tests/test_clients.py
- commerce_coordinator/apps/stripe/tests/test_pipeline.py
- commerce_coordinator/apps/stripe/tests/test_views.py
- commerce_coordinator/apps/stripe/views.py
- commerce_coordinator/apps/titan/clients.py
- commerce_coordinator/apps/titan/pipeline.py
- commerce_coordinator/apps/titan/signals.py
- commerce_coordinator/apps/titan/tasks.py
- commerce_coordinator/apps/titan/tests/test_clients.py
- commerce_coordinator/apps/titan/tests/test_pipeline.py
- commerce_coordinator/apps/titan/tests/test_tasks.py
- commerce_coordinator/settings/local.py
- commerce_coordinator/settings/test.py
**Description:**
* Added `providerResponseBody` in titan payment update calls.
* Also Added `edxLmsUserId` and `orderUuid` in titan payment update calls.
* rename `responseCode` to `referenceNumber`.
* Updated stripe update call to save `edx_lms_user_id` in metadata.
* Added check for source_system in Stripe Webhook.
**JIRA:** [THES-195](https://2u-internal.atlassian.net/browse/THES-195)
> feat: Added providerResponseBody in titan update calls.

- commerce_coordinator/apps/core/constants.py
- commerce_coordinator/apps/frontend_app_payment/filters.py
- commerce_coordinator/apps/frontend_app_payment/tests/test_filters.py
- commerce_coordinator/apps/frontend_app_payment/tests/test_views.py
- commerce_coordinator/apps/stripe/exceptions.py
- commerce_coordinator/apps/stripe/pipeline.py
- commerce_coordinator/apps/stripe/tests/test_pipeline.py
- commerce_coordinator/apps/titan/pipeline.py
- commerce_coordinator/apps/titan/tests/test_clients.py
- commerce_coordinator/apps/titan/tests/test_pipeline.py
- commerce_coordinator/settings/base.py
- In stripe Coordinator app:
- Implement clients.StripeAPIClient.retrieve_payment_intent
- Create unit tests for client 
- Implement pipeline.GetStripeDraftPayment
- Create unit tests for pipeline step
- Connect frontend-app-payment.filters.DraftPaymentRequested to pipeline.GetStripeDraftPayment
```mermaid
sequenceDiagram
participant P as Payment MFE
participant C as Coordinator
participant T as Titan
participant S as Stripe
P->>+C: Create or Get Draft Payment
C-->>-P: (response)
C->>+T: Get Active Order
T-->>-C: (response)
alt Active, unpaid payment found from Titan
rect rgb(255, 245, 173, .25)
note over T: New:
C->>+S: Get Draft Payment
S-->>-C: (response)
end
C-->>P: (response with payment_number and order_uuid)
end
```
* Jira: …
> feat: add stripe.pipeline.GetStripeDraftPayment

- commerce_coordinator/apps/core/constants.py
- commerce_coordinator/apps/stripe/pipeline.py
- commerce_coordinator/apps/titan/pipeline.py
- commerce_coordinator/apps/titan/tests/test_pipeline.py
Fix-forwards for https://github.com/edx/commerce-coordinator/pull/108:
- Add `PipelineCommand` Enum so it's clearer what `return {}` or `return None` is intended to do in the context of a `PipelineStep`.
- Add debug logging for ValidateOrderReadyForDraftPayment
* Jira: [THES-215](https://2u-internal.atlassian.net/browse/THES-215)
* Fix-forwards: https://github.com/edx/commerce-coordinator/pull/108
> refactor: add PipelineCommand Enum & convert comments to debug messages

- commerce_coordinator/apps/core/tests/test_cache.py
- commerce_coordinator/apps/frontend_app_payment/exceptions.py
- commerce_coordinator/apps/frontend_app_payment/serializers.py
- commerce_coordinator/apps/frontend_app_payment/tests/test_filters.py
- commerce_coordinator/apps/frontend_app_payment/tests/test_views.py
- commerce_coordinator/apps/frontend_app_payment/views.py
- commerce_coordinator/apps/stripe/constants.py
- commerce_coordinator/apps/stripe/tests/test_pipeline.py
- commerce_coordinator/apps/stripe/tests/test_views.py
- commerce_coordinator/apps/stripe/views.py
- commerce_coordinator/apps/titan/serializers.py
- commerce_coordinator/apps/titan/tests/test_clients.py
- commerce_coordinator/apps/titan/tests/test_pipeline.py
- commerce_coordinator/apps/titan/tests/test_tasks.py
**Description:** Created utility function that converts a Titan’s payment providerResponseBody for a Stripe payment or a Titan API response into the format required by the [feedback module](https://github.com/openedx/frontend-app-payment/blob/2u/project-theseus/docs/how_tos/feedback.rst) in Payment MFE
**JIRA:** [THES-247](https://2u-internal.atlassian.net/browse/THES-247)
> feat: Returning new_payment_number and errors from get payment API.

- .github/workflows/ci.yml
- commerce_coordinator/apps/core/admin.py
- tox.ini
- PR created under the issue https://github.com/edx/edx-arch-experiments/issues/457
- Added support to run CI tests with Django 4.2
> feat: add django42 support

- commerce_coordinator/settings/base.py
**Description:** 
Remove unused JWT_AUTH_REFRESH_COOKIE setting. This setting was never actually used, so there is no timing issues.
See DEPR for details:
https://github.com/openedx/public-engineering/issues/190
> fix: remove JWT_AUTH_REFRESH_COOKIE

- Dockerfile
Add git & alphabetize installed packages in Dockerfile.
Due to following error on deploy:
Collecting commercetools@ git+https://github.com/edx/commercetools-python-sdk.git@36639f4a196d7fc0daecf914ee46f42229087abb (from -r requirements/production.txt (line 70))
Cloning https://github.com/edx/commercetools-python-sdk.git (to revision 36639f4a196d7fc0daecf914ee46f42229087abb) to /tmp/pip-install-u2dcvnx4/commercetools_cdad0154d7824963bfdfe8c00e11493f
ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
The command '/bin/sh -c pip install -r requirements/production.txt' returned a non-zero code: 1
We need this because we use a fork of edx/commercetools-python-sdk that is not …
> fix: [SONIC-169] add git & alphabetize installed packages in Dockerfile

- commerce_coordinator/apps/commercetools/serializers.py
- commerce_coordinator/apps/commercetools/signals.py
- commerce_coordinator/apps/commercetools/tests/constants.py
- commerce_coordinator/apps/commercetools/tests/test_views.py
- commerce_coordinator/apps/commercetools/views.py
- commerce_coordinator/apps/lms/signals.py
- commerce_coordinator/apps/lms/tasks.py
- commerce_coordinator/apps/lms/tests/constants.py
- commerce_coordinator/apps/lms/tests/test_signals.py
- commerce_coordinator/apps/lms/tests/test_tasks.py
- commerce_coordinator/apps/titan/serializers.py
- commerce_coordinator/apps/titan/tests/constants.py
- commerce_coordinator/apps/titan/views.py
- commerce_coordinator/settings/base.py
[SONIC-117](https://2u-internal.atlassian.net/browse/SONIC-117)
This PR adds unit tests for the fulfillment view added in [SONIC-120](https://2u-internal.atlassian.net/browse/SONIC-120)
It also adds a new source_system attribute to the fulfillment lms call
Added config for commercetools signal
> feat: [SONIC-117] Add source system to ct fulfillment and update ct fulfillment tests

- commerce_coordinator/apps/enterprise_learner/enterprise_client.py
- commerce_coordinator/apps/enterprise_learner/tests/test_enterprise_client.py
- commerce_coordinator/apps/enterprise_learner/tests/test_utils.py
- commerce_coordinator/apps/enterprise_learner/utils.py
- commerce_coordinator/apps/lms/tests/test_views.py
- commerce_coordinator/apps/rollout/pipeline.py
- commerce_coordinator/settings/base.py
- commerce_coordinator/settings/devstack.py
- commerce_coordinator/settings/local.py
- commerce_coordinator/settings/test.py
**Description**: Configured `enterprise_client` that checks whether a user is enterprise or not. Enterprise users will then be redirected to legacy.
**JIRA**: [SONIC-124](https://2u-internal.atlassian.net/browse/SONIC-124)
> feat: Added client that checks for enterprise users

- commerce_coordinator/apps/commercetools/catalog_info/utils.py
- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/tests/catalog_info/test_utils.py
Description
Verified the current implementation to retrieve the customers order history from Commercetools is functioning correctly and have modified the implementation to only fetch completed orders.
JIRA
https://2u-internal.atlassian.net/browse/SONIC-128
> feat: Modified CT order history implementation

- commerce_coordinator/apps/commercetools/tests/test_views.py
- commerce_coordinator/apps/commercetools/views.py
Add tests and permission flags for /commercetools/fulfill view to be restricted only to staff users.
* Jira: [SONIC-268](https://2u-internal.atlassian.net/browse/SONIC-268)
> fix: restrict commercetools /fulfill view to staff users

- commerce_coordinator/apps/commercetools/tests/test_views.py
- commerce_coordinator/apps/commercetools/views.py
Reverts edx/commerce-coordinator#166.
Adding authentication on this endpoint did not work because AWS EventBridge, which communicates with this endpoint, is authenticating by sending a header like `Authorization: Bearer <token>`.
Unfortunately, the edx-drf-extensions' [JwtAuthentication](https://github.com/openedx/edx-drf-extensions/blob/master/edx_rest_framework_extensions/auth/jwt/authentication.py) class is default-configured to recognize `Authorization: JWT <token>`, as that is how the MFEs are set up.
We can try to change [JWT_AUTH_HEADER_PREFIX](https://styria-digital.github.io/django-rest-framework-jwt/#jwt_auth_header_prefix), but will revert first so other work can continue to be performed with fulfillment in the pipeline.
I also tried to use edx-drf-extensions' …
> Revert "fix: restrict commercetools /fulfill view to staff users"

- commerce_coordinator/apps/commercetools/catalog_info/constants.py
- commerce_coordinator/apps/commercetools/catalog_info/utils.py
- commerce_coordinator/apps/commercetools/data.py
- commerce_coordinator/apps/commercetools/tests/test_data.py
- commerce_coordinator/apps/frontend_app_ecommerce/tests/test_views.py
- commerce_coordinator/apps/frontend_app_ecommerce/views.py
- commerce_coordinator/settings/devstack.py
- commerce_coordinator/settings/local.py
- Added settings for future formatting
- Updating local settings to use the provisioned key name, even though it fails the standard format by having an underscore
- Updating devstack to not use sqlite
> fix: matching f-a-ecomms returns exactly

- commerce_coordinator/apps/commercetools/authentication.py
- commerce_coordinator/apps/commercetools/tests/test_authentication.py
- commerce_coordinator/apps/commercetools/tests/test_views.py
- commerce_coordinator/apps/commercetools/views.py
- commerce_coordinator/settings/local.py
- docs/commerce_coordinator.apps.commercetools.rst
- docs/commerce_coordinator.apps.ecommerce.rst
- docs/how_tos.rst
- docs/how_tos/using_ngrok.rst
- docs/index.rst
- ngrok.yml
The views for the Commercetools app are implemented to allow an external service configured with a Commercetools Subscription, like AWS EventBridge, to send Commercetools Messages to Coordinator.
AWS EventBridge supports retrieving a token from an OAuth2 service. In this case, we have instructed it to get a token from LMS. However, AWS EventBridge will expect that the consuming API Destination perform authorization by expecting a header like:
Authorization: Bearer <token>
Coordinator is configured to expect headers like:
Authorization: JWT <token>
Because this is what other MFEs use.
This commit adds class `JwtBearerAuthentication` to allow Coordinator to expect the new header format, as well as enforce that authentication method on existing views in Coordinator's Commercetools app.
* …
> feat: add authentication for commercetools views

- commerce_coordinator/apps/commercetools/catalog_info/constants.py
- commerce_coordinator/apps/commercetools/catalog_info/foundational_types.py
- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/management/commands/provision_order_states.py
- commerce_coordinator/apps/commercetools/serializers.py
- commerce_coordinator/apps/commercetools/signals.py
- commerce_coordinator/apps/commercetools/sub_messages/signals_delayed.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tasks.py
- commerce_coordinator/apps/commercetools/tests/conftest.py
- commerce_coordinator/apps/commercetools/tests/constants.py
- commerce_coordinator/apps/commercetools/tests/mocks.py
- commerce_coordinator/apps/commercetools/tests/sub_messages/test_signals_delayed.py
- commerce_coordinator/apps/commercetools/tests/sub_messages/test_tasks.py
- commerce_coordinator/apps/commercetools/tests/test_clients.py
- commerce_coordinator/apps/commercetools/tests/test_signals.py
- commerce_coordinator/apps/commercetools/tests/test_tasks.py
- commerce_coordinator/apps/commercetools/views.py
- commerce_coordinator/apps/lms/clients.py
- commerce_coordinator/apps/lms/signal_handlers.py
- commerce_coordinator/apps/lms/signals.py
- commerce_coordinator/apps/lms/tasks.py
- commerce_coordinator/apps/lms/tests/constants.py
- commerce_coordinator/apps/lms/tests/test_clients.py
- commerce_coordinator/apps/lms/tests/test_signals.py
- commerce_coordinator/apps/lms/tests/test_tasks.py
- commerce_coordinator/apps/rollout/pipeline.py
- commerce_coordinator/settings/base.py
Created new LineItemStates in Commercetools with accompanying transitions to track fulfillment process. Coordinator triggers fulfillment on “Fulfillment Pending” events when a Commercetools message is received from the AWS Eventbridge. Based on fulfillment result, the LineItemState is also transitioned to a success or failure state. Initially transitioning the state to 'Fulfillment Pending' is handle in this [PR](https://github.com/frontastic-developers/customer-twou/pull/98/) in the Commercetools twou repo
[SONIC-270](https://2u-internal.atlassian.net/browse/SONIC-270)
> feat: Transition LineItemState on fulfillment

- commerce_coordinator/apps/commercetools/serializers.py
**Description**: Removed 'returnTrackingId' and 'returnDate' from serializer because it's optional fields.
**JIRA**: [SONIC-484](https://2u-internal.atlassian.net/browse/SONIC-484)
> feat: Removed 'returnTrackingId' and 'returnDate' from serializer

- commerce_coordinator/apps/commercetools/signals.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tasks.py
- commerce_coordinator/apps/commercetools/tests/constants.py
- commerce_coordinator/apps/commercetools/tests/test_signals.py
- commerce_coordinator/apps/commercetools/tests/test_tasks.py
- commerce_coordinator/apps/commercetools/views.py
- commerce_coordinator/apps/core/views.py
- commerce_coordinator/apps/rollout/utils.py
- commerce_coordinator/apps/stripe/constants.py
- commerce_coordinator/apps/stripe/signals.py
- commerce_coordinator/apps/stripe/tests/test_views.py
- commerce_coordinator/apps/stripe/views.py
Updated the Stripe Webhookview to listen to the 'charge.refunded' event for if someone makes a refund directly from the Stripe dashboard. If it is a CT order, we create a refund transaction for it.
Ticket: https://2u-internal.atlassian.net/browse/SONIC-504
Functionality information ticket: https://2u-internal.atlassian.net/browse/SONIC-520
> feat: CT refund transaction from Stripe dashboard refund

- commerce_coordinator/apps/commercetools/tasks.py
- commerce_coordinator/apps/commercetools/tests/conftest.py
- commerce_coordinator/apps/commercetools/tests/test_tasks.py
- commerce_coordinator/apps/commercetools/tests/test_utils.py
- commerce_coordinator/apps/commercetools/utils.py
- commerce_coordinator/settings/base.py
- commerce_coordinator/settings/test.py
Fix following #234 and #240 which adds a check for any existing full refunds before creating a refund transaction when a `charge.refunded` stripe event fires, ensuring no duplicate refund transaction records on the Merchant Center. The signal configuration is also added to `base.py` again.
JIRA: https://2u-internal.atlassian.net/browse/SONIC-589
> fix: added check for duplicate refund transactions

- commerce_coordinator/apps/commercetools/serializers.py
- commerce_coordinator/apps/commercetools/sub_messages/signals_delayed.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tests/sub_messages/test_signals_delayed.py
- commerce_coordinator/apps/commercetools/tests/sub_messages/test_tasks.py
- commerce_coordinator/apps/commercetools/views.py
- commerce_coordinator/apps/lms/clients.py
- commerce_coordinator/apps/lms/signal_handlers.py
- commerce_coordinator/apps/lms/tasks.py
- commerce_coordinator/apps/lms/tests/constants.py
- commerce_coordinator/apps/lms/tests/test_clients.py
- commerce_coordinator/apps/lms/tests/test_signals.py
- commerce_coordinator/apps/lms/tests/test_tasks.py
**Description**: Added logging for fulfillment successes and failures.
**JIRA**: [SONIC-299](https://2u-internal.atlassian.net/browse/SONIC-299)
> feat: Added logging for fulfillment events

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/filters.py
- commerce_coordinator/apps/commercetools/pipeline.py
- commerce_coordinator/apps/commercetools/serializers.py
- commerce_coordinator/apps/commercetools/sub_messages/signals_delayed.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tests/sub_messages/test_signals_delayed.py
- commerce_coordinator/apps/commercetools/tests/sub_messages/test_tasks.py
- commerce_coordinator/apps/commercetools/tests/test_clients.py
- commerce_coordinator/apps/commercetools/tests/test_pipeline.py
- commerce_coordinator/apps/commercetools/views.py
- commerce_coordinator/apps/lms/clients.py
- commerce_coordinator/apps/lms/tests/test_clients.py
- commerce_coordinator/apps/lms/views.py
- commerce_coordinator/apps/stripe/pipeline.py
**Description**: Additional logging for views and client flows
**JIRA**: https://2u-internal.atlassian.net/browse/SONIC-344
> feat: additional logging

- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tests/sub_messages/test_tasks.py
- commerce_coordinator/apps/commercetools/views.py
- Adding new info's
- Propagating Message IDs to logs
- Converting some important debugs to info
> fix: more logging in tasks in prep for 100% catalog.

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/tests/conftest.py
- commerce_coordinator/apps/commercetools/tests/test_clients.py
- commerce_coordinator/apps/lms/tasks.py
- commerce_coordinator/apps/lms/tests/test_tasks.py
**Description**: Added missing tests from https://github.com/edx/commerce-coordinator/pull/182 previously covered by `pragma no cover`.
**JIRA**: [SONIC-449](https://2u-internal.atlassian.net/browse/SONIC-449)
> feat: added missing tests

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/pipeline.py
- commerce_coordinator/apps/commercetools/tests/conftest.py
- commerce_coordinator/apps/commercetools/tests/test_clients.py
- commerce_coordinator/apps/commercetools/tests/test_pipeline.py
- commerce_coordinator/apps/commercetools/tests/test_utils.py
- commerce_coordinator/apps/commercetools/utils.py
- commerce_coordinator/apps/lms/filters.py
- commerce_coordinator/apps/lms/serializers.py
- commerce_coordinator/apps/lms/tests/test_views.py
- commerce_coordinator/apps/lms/urls.py
- commerce_coordinator/apps/lms/views.py
- commerce_coordinator/settings/base.py
Get in user id from LMS of a user, who has requested their account be deleted, to anonymize PII fields of their Commercetools customer object in relation to GDPR.
Ticket: https://2u-internal.atlassian.net/browse/SONIC-561
> feat: Anonymizing CT customer data on LMS account deletion

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/pipeline.py
- commerce_coordinator/apps/commercetools/tests/test_clients.py
- commerce_coordinator/apps/commercetools/tests/test_pipeline.py
- commerce_coordinator/apps/commercetools/tests/test_utils.py
- commerce_coordinator/apps/commercetools/utils.py
> feat: Add transaction id to returnitem, returnitemid to transaction

- README.rst
- commerce_coordinator/settings/local.py
> Update README.rst with set up of CT

- .gitignore
- commerce_coordinator/apps/core/models.py
- commerce_coordinator/apps/core/tests/test_models.py
- commerce_coordinator/apps/frontend_app_ecommerce/views.py
- commerce_coordinator/apps/lms/tasks.py
- commerce_coordinator/apps/lms/views.py
> fix: fix lms_user_id population

- commerce_coordinator/apps/commercetools/catalog_info/constants.py
- commerce_coordinator/apps/commercetools/catalog_info/foundational_types.py
- commerce_coordinator/apps/commercetools/management/commands/create_paypal_custom_types.py
> feat: [SONIC-650] Added PayPal custom attributes management command

- commerce_coordinator/apps/commercetools/catalog_info/constants.py
- commerce_coordinator/apps/commercetools/catalog_info/foundational_types.py
- commerce_coordinator/apps/commercetools/management/commands/create_returnitem_custom_type.py
- commerce_coordinator/apps/commercetools/management/commands/create_transaction_custom_type.py
> feat: [SONIC-724] Add scripts for adding custom fields to returnitem and transaction

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/pipeline.py
- commerce_coordinator/apps/commercetools/tests/_test_cases.py
- commerce_coordinator/apps/commercetools/tests/test_pipeline.py
- commerce_coordinator/apps/frontend_app_ecommerce/views.py
> SONIC-740: get customer_id only if not passed in params

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tests/test_clients.py
- commerce_coordinator/apps/commercetools/utils.py
> fix: commercetools errors

- commerce_coordinator/apps/frontend_app_ecommerce/tests/test_views.py
- commerce_coordinator/apps/frontend_app_ecommerce/views.py
**Description**
Gracefully handle exception in legacy and CT endpoints for combined order history
[SONIC-788](https://2u-internal.atlassian.net/browse/SONIC-788)
> fix: handled exception gracefully and returned proper response

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/pipeline.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/lms/tasks.py
> SONIC-740: Added logs to note time for Commercetools calls

- commerce_coordinator/apps/commercetools/tasks.py
Stop creating duplicate refund transaction for paypal
> fix: multiple paypal refund transactions bug

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tests/constants.py
- commerce_coordinator/apps/commercetools/tests/sub_messages/test_tasks.py
- commerce_coordinator/apps/commercetools/tests/test_clients.py
update line items state in single api call in fulfillment task
> feat: update line items state in single api call

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/paypal/clients.py
- commerce_coordinator/apps/paypal/pipeline.py
- commerce_coordinator/settings/base.py
This PR fixes the paypal refund `RequestException('[ClientCredentialsAuth: OAuthToken is undefined or expired.]')` error on prod environment.
> fix: PayPal refund bug on prod

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tasks.py
- commerce_coordinator/apps/commercetools/tests/test_clients.py
- commerce_coordinator/apps/commercetools/tests/test_tasks.py
- commerce_coordinator/apps/commercetools/utils.py
- commerce_coordinator/apps/commercetools/views.py
- commerce_coordinator/apps/core/clients.py
- commerce_coordinator/apps/core/views.py
- commerce_coordinator/apps/ecommerce/clients.py
- commerce_coordinator/apps/lms/clients.py
- commerce_coordinator/apps/lms/tasks.py
- commerce_coordinator/apps/titan/clients.py
In this PR, we have enhanced the log messages and adjusted the log levels in the commerce-coordinator. Additionally, we need to review the retry criteria for various tasks triggered by the CT commerce flow to determine if any additional errors should be included in the retry logic.
> fix: Improve logging messages

- commerce_coordinator/apps/lms/views.py
> fix: removed throttling for FirstTimeDiscountEligibleView

- commerce_coordinator/apps/core/admin.py
> temp: add lms_user_id to django admin

- commerce_coordinator/apps/commercetools/catalog_info/edx_utils.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tests/conftest.py
- commerce_coordinator/apps/commercetools/tests/sub_messages/test_tasks.py
- Properly mock payment object
- make get payment id generic
> fix: improve payment mock in test

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/lms/views.py
- commerce_coordinator/apps/rollout/pipeline.py
- commerce_coordinator/apps/rollout/waffle.py
The existing pipeline has been updated. It checks the program's availability; if the program is available in CT, it will remain to CT. If it's not available, it will move to the legacy system. All of this functionality has been implemented behind a feature flag.
> fix: update payment page redirect for program

- commerce_coordinator/apps/commercetools/management/commands/find_ct_pending_fulfillment_non_refunded_orders.py
> feat: add pending fulfillment management command

- commerce_coordinator/apps/commercetools/catalog_info/edx_utils.py
- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/filters.py
- commerce_coordinator/apps/commercetools/pipeline.py
- commerce_coordinator/apps/commercetools/serializers.py
- commerce_coordinator/apps/commercetools/sub_messages/signals_delayed.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tasks.py
- commerce_coordinator/apps/commercetools/tests/catalog_info/test_edx_utils.py
- commerce_coordinator/apps/commercetools/tests/conftest.py
- commerce_coordinator/apps/commercetools/tests/raw_ct_program_order.json
- commerce_coordinator/apps/commercetools/tests/sub_messages/test_signals_delayed.py
- commerce_coordinator/apps/commercetools/tests/sub_messages/test_tasks.py
- commerce_coordinator/apps/commercetools/tests/test_clients.py
- commerce_coordinator/apps/commercetools/tests/test_pipeline.py
- commerce_coordinator/apps/commercetools/tests/test_tasks.py
- commerce_coordinator/apps/commercetools/utils.py
- commerce_coordinator/apps/commercetools/views.py
- commerce_coordinator/apps/paypal/clients.py
- commerce_coordinator/apps/paypal/pipeline.py
- commerce_coordinator/apps/rollout/tests/test_pipeline.py
- commerce_coordinator/apps/rollout/tests/test_util_functions.py
- commerce_coordinator/apps/rollout/utils.py
- commerce_coordinator/settings/test.py
- tox.ini
Ticket:
[Part of program(entitled course) refunds in Commerce Coordinator](https://2u-internal.atlassian.net/browse/SONIC-839)
> feat: part of program refund with single transaction

- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tests/sub_messages/test_tasks.py
Emit error message on fulfill_order_placed_message_signal_task failure and emit DD alert on this error log.
> feat: log error on order fulfill task failed

- commerce_coordinator/apps/commercetools/catalog_info/edx_utils.py
- commerce_coordinator/apps/commercetools/data.py
- commerce_coordinator/apps/commercetools/pipeline.py
- commerce_coordinator/apps/commercetools/tests/test_pipeline.py
- commerce_coordinator/settings/local.py
when order is enrollmentcode order, the `order.paymentInfo` is null
we access order.paymentInfo at 3 places in CC
- While getting orders for order history page
- While refunding the order
- While getting receipt URL for the order (already handled gracefully)
This PR gracefully handle the areas
> feat: handle enrollment code orders gracefully

- commerce_coordinator/apps/commercetools/tests/test_views.py
- commerce_coordinator/apps/commercetools/views.py
The fulfill_placed_order_signal_task Celery task is being triggered twice, which should not be happening. This occurs because AWS emits LineItemTransitionState signals simultaneously within a second, causing multiple executions of the task.
This PR makes sure the task is not triggered more than once.
> fix: concurrency issue in fulfillment task

- commerce_coordinator/apps/commercetools/http_api_client.py
- commerce_coordinator/apps/commercetools/tests/test_http_api_client.py
Fix errors and put retries on CT calls in program price api view
> fix: improve ct call in program price api

- commerce_coordinator/apps/commercetools/serializers.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/lms/signal_handlers.py
- commerce_coordinator/apps/lms/tasks.py
- commerce_coordinator/apps/lms/tests/constants.py
- commerce_coordinator/apps/lms/tests/test_signals.py
- commerce_coordinator/apps/lms/tests/test_tasks.py
Reverts edx/commerce-coordinator#380
> Revert "fix: fallback for user first name empty"

- commerce_coordinator/settings/local.py
- commerce_coordinator/settings/production.py
- commerce_coordinator/settings/utils.py
We are moving the logging format string to the remote config to fix the logging issue locally.
We can set LOGGING_FORMAT_STRING in our private.py file to get logs for local env like:
`LOGGING_FORMAT_STRING = '%(asctime)s %(levelname)s %(process)d [%(name)s] [user %(userid)s] [ip %(remoteip)s] %(filename)s:%(lineno)d - %(message)s`'
[edx-internal](https://github.com/edx/edx-internal/pull/12516)
> fix: fix log stream issue locally

- commerce_coordinator/apps/commercetools/clients.py
- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tests/sub_messages/test_tasks.py
- commerce_coordinator/apps/commercetools/tests/test_clients.py
- commerce_coordinator/apps/commercetools/tests/test_utils.py
- commerce_coordinator/apps/commercetools/utils.py
- commerce_coordinator/apps/iap/views.py
For mobile orders, we want to simply create a return and mark it refunded without doing any psp refund.
> feat: gracefully handle mobile order refund in CC

- commerce_coordinator/apps/commercetools/http_api_client.py
- commerce_coordinator/apps/lms/tests/test_utils.py
- commerce_coordinator/apps/lms/utils.py
- Get the updated key cartPredicate from the cart discount object 
- Get all active cart discounts
> fix: fix cart discount key to get cartPredicate

- commerce_coordinator/apps/commercetools/sub_messages/tasks.py
- commerce_coordinator/apps/commercetools/tests/sub_messages/test_tasks.py
- commerce_coordinator/apps/commercetools/tests/test_utils.py
- commerce_coordinator/apps/commercetools/utils.py
- requirements/base.in
- requirements/base.txt
- requirements/common_constraints.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
Hide receipt button for mobile order 
format external price as price 
in order confirmation email for mobile order
> feat: format price for different currencies in email

- commerce_coordinator/apps/commercetools/pipeline.py
- commerce_coordinator/apps/commercetools/tests/test_pipeline.py
- commerce_coordinator/apps/lms/tests/test_views.py
- commerce_coordinator/apps/lms/views.py
fixes `AttributeError: 'NoneType' object has no attribute 'first_name'` error
> fix: handle 500 error in user retirement view

- commerce_coordinator/apps/commercetools/utils.py
- commerce_coordinator/apps/iap/segment_events.py
- commerce_coordinator/apps/iap/tests/test_segment_events.py
- commerce_coordinator/apps/iap/views.py
[EDUN-6007 ](https://redventures.atlassian.net/browse/EDUN-6007)
description: 
All events in systems need to have the multi_item_cart_enabled boolean added
For Standard Segment events, make sure they can handle multiple products in payload
For Non-standard custom events, verify they do not break, but no need to update them
> feat: add multi_item_cart eventing
